name: Bug Report
description: Open a bug issue
title: "[Bug]: "
labels: ["bug"]
assignees:
  - MatteoCampinoti94
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the program where you running?
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Summarize the bug encountered concisely
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug?
      description: Summarize the steps to encounter the bug
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell